import { NextRequest, NextResponse, after } from 'next/server';
import type {
  FeedSuccessResponse,
  FeedErrorResponse,
  FeedWord,
} from '@/app/home/_lib/types';
import type { TargetLanguage } from '@/app/_lib/wordTypes';
import { LANG_PROMPT } from '@/app/api/_lib/languagePrompt';
import { parseFeedResponse } from './parseFeedResponse';
import crypto from 'crypto';
import { supabaseServer } from '@/app/_lib/supabaseServer';
import { getProcessedQuery, fetchPexelsImage } from '@/app/api/_lib/pexels';

const VALID_LANGUAGES: TargetLanguage[] = ['english'];

const KKU_API_URL = 'https://gen.ai.kku.ac.th/api/v1/chat/completions';
const API_TIMEOUT_MS = 30_000;

type FeedErrorType = FeedErrorResponse['error']['type'];

const ERROR_MESSAGES: Record<FeedErrorType, string> = {
  invalid_input: 'Invalid input.',
  api_error: 'Failed to generate word. Please try again.',
  rate_limit: 'Too many requests. Please wait a moment.',
  timeout: 'Connection timed out. Please try again.',
  network_error: 'Cannot connect. Please check your internet.',
};

function errorResponse(
  type: FeedErrorType,
  status: number
): NextResponse<FeedErrorResponse> {
  return NextResponse.json(
    { error: { type, message: ERROR_MESSAGES[type] } },
    { status }
  );
}

/**
 * Validate that the request body has the expected shape:
 * - language: TargetLanguage
 * - excludeWords: string[]
 * - count: positive integer
 */
function validateInput(
  body: unknown
): { language: TargetLanguage; excludeWords: string[]; count: number; topic?: string } | null {
  if (typeof body !== 'object' || body === null) return null;

  const record = body as Record<string, unknown>;

  // language must be a valid TargetLanguage
  if (typeof record.language !== 'string') return null;
  if (!VALID_LANGUAGES.includes(record.language as TargetLanguage)) return null;

  // excludeWords must be an array of strings
  if (!Array.isArray(record.excludeWords)) return null;
  if (!record.excludeWords.every((item) => typeof item === 'string'))
    return null;

  // count must be a positive integer
  if (typeof record.count !== 'number') return null;
  if (!Number.isInteger(record.count) || record.count <= 0) return null;

  const topic = typeof record.topic === 'string' ? record.topic : undefined;

  return {
    language: record.language as TargetLanguage,
    excludeWords: record.excludeWords as string[],
    count: record.count,
    topic,
  };
}

/**
 * Build the prompt that asks the KKU AI to generate a pool of vocabulary words
 * for the target language, tailored to Thai learners. The model is asked to
 * avoid `excludeWords` and (optionally) stay on `topic`, and to return a JSON
 * array that `parseFeedResponse` can consume.
 */
function buildFeedPrompt(
  language: TargetLanguage,
  excludeWords: string[],
  poolSize: number,
  topic?: string
): string {
  const spec = LANG_PROMPT[language];
  const topicLine = topic
    ? `All words must relate to the topic: "${topic}".`
    : 'Pick common, useful everyday words across varied themes.';
  const excludeLine =
    excludeWords.length > 0
      ? `Do NOT include any of these words (already learned): ${excludeWords.slice(0, 200).join(', ')}.`
      : '';

  return [
    `You are a vocabulary generator for a Thai person learning ${spec.label}.`,
    `Generate ${poolSize} distinct ${spec.label} vocabulary words.`,
    topicLine,
    excludeLine,
    'Return ONLY a JSON array (no markdown, no prose). Each element must be an object with these fields:',
    '- "word": the ' + spec.label + ' word.',
    '- "ipa": its IPA phonetic transcription.',
    '- "thai": its meaning in Thai.',
    '- "part_of_speech": the part of speech written in Thai (e.g. คำนาม, คำกริยา).',
    '- "image_queries": an array of exactly 3 short English phrases for finding a representative photo of the word.',
  ]
    .filter(Boolean)
    .join('\n');
}

export async function POST(
  request: NextRequest
): Promise<NextResponse<FeedSuccessResponse | FeedErrorResponse>> {
  // Parse request body
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return errorResponse('invalid_input', 400);
  }

  // Validate input
  const input = validateInput(body);
  if (!input) {
    return errorResponse('invalid_input', 400);
  }

  const { language, excludeWords, count, topic } = input;

  // Per-user AI credentials (fall back to env). Words are generated by the AI.
  const customApiKey = request.headers.get('x-custom-api-key');
  const customModel = request.headers.get('x-custom-model');
  const model = customModel || 'deepseek-v4-flash';
  const topicKey = topic ? topic.toLowerCase().trim() : '';

  // Cache key for the image-resolved pool stored in ai_feed_pool_cache.
  const cacheRawString = [model, language, topicKey].join(':');
  const cacheKey = crypto.createHash('sha256').update(cacheRawString).digest('hex');

  // Exclusion check helper
  const isExcluded = (word: any) => {
    const normalizedExclude = excludeWords.map((w) => w.toLowerCase().trim());
    const checkFields = [
      word.word,
      word.thai,
    ]
      .filter(Boolean)
      .map((f) => f.toLowerCase().trim());

    return checkFields.some((field) => normalizedExclude.includes(field));
  };

  // Try to load cached pool
  let cachedWords: FeedWord[] | null = null;
  try {
    const { data: cachedData, error: cacheErr } = await supabaseServer
      .from('ai_feed_pool_cache')
      .select('words')
      .eq('cache_key', cacheKey)
      .gt('expires_at', new Date().toISOString())
      .single();

    if (cachedData && !cacheErr && Array.isArray(cachedData.words)) {
      cachedWords = cachedData.words as FeedWord[];
    }
  } catch (err) {
    console.error('[feed] Cache lookup failed:', err);
  }

  if (cachedWords) {
    const filtered = cachedWords.filter((w) => !isExcluded(w));
    if (filtered.length >= count) {
      console.log(
        `[feed] Cache HIT for key: ${cacheKey}. Serving ${count} words from pool of ${filtered.length}.`
      );
      return NextResponse.json({ words: filtered.slice(0, count) }, { status: 200 });
    }
    console.log(
      `[feed] Cache pool exhausted or too small (available: ${filtered.length}, requested: ${count}). Regenerating pool...`
    );
  }

  const apiKey = customApiKey || process.env.KKU_API_KEY;
  if (!apiKey) {
    console.error('[feed] Missing API key');
    return errorResponse('api_error', 401);
  }

  // Generate a pool larger than `count` so it can absorb future exclusions and
  // be reused from cache before regenerating.
  const poolSize = Math.max(count, 12);
  const prompt = buildFeedPrompt(language, excludeWords, poolSize, topic);

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), API_TIMEOUT_MS);

  try {
    // Generate the word pool with the KKU AI.
    const response = await fetch(KKU_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [{ role: 'user' as const, content: prompt }],
        max_tokens: 4096,
      }),
      signal: controller.signal,
    });
    clearTimeout(timeoutId);

    if (!response.ok) {
      console.error(`[feed] KKU API error [${response.status}]`);
      return errorResponse('api_error', 502);
    }

    const responseText = await response.text();
    let content: string | undefined;
    try {
      const data = JSON.parse(responseText);
      content = data?.choices?.[0]?.message?.content ?? data?.content;
    } catch {
      // fall through to empty-content handling
    }

    const words = content ? parseFeedResponse(content, language) : [];

    // AI returned nothing usable — nothing to serve.
    if (words.length === 0) {
      return NextResponse.json({ words: [] }, { status: 200 });
    }

    // Fetch image URLs for each word
    const wordsWithImages = await Promise.all(
      words.map(async (word) => {
        const queries = word.imageQueries || [];
        const imageUrls: string[] = [];

        for (const query of queries) {
          let imageUrl: string | undefined;
          const processedQuery = getProcessedQuery(query);

          if (process.env.PEXELS_API_KEY) {
            const pexelsUrl = await fetchPexelsImage(query);
            if (pexelsUrl) {
              imageUrl = pexelsUrl;
            }
          }

          // Fallback to LoremFlickr search if Pexels key is not set or Pexels returns no image
          if (!imageUrl) {
            imageUrl = `https://loremflickr.com/600/400/${encodeURIComponent(processedQuery)}`;
          }

          imageUrls.push(imageUrl);
        }

        return {
          ...word,
          imageUrl: imageUrls[0],
          imageUrls,
        };
      })
    );

    // Save the new pool to database cache (asynchronously)
    const expiresAt = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000); // 3 days
    after(async () => {
      try {
        const { error: saveErr } = await supabaseServer
          .from('ai_feed_pool_cache')
          .upsert({
            cache_key: cacheKey,
            language,
            topic: topicKey,
            model,
            words: wordsWithImages,
            expires_at: expiresAt.toISOString(),
          }, { onConflict: 'cache_key' });

        if (saveErr) {
          console.error('[feed] Cache pool write error:', saveErr);
        } else {
          console.log(`[feed] Cache pool stored for key: ${cacheKey}`);
        }
      } catch (err) {
        console.error('[feed] Cache pool write failed:', err);
      }
    });

    // Filter out words the user has already seen/rejected and return up to
    // `count`. When nothing new remains, return an empty array — the client
    // treats this as "all words learned" rather than recycling duplicates.
    const filtered = wordsWithImages.filter((w) => !isExcluded(w));
    return NextResponse.json({ words: filtered.slice(0, count) }, { status: 200 });
  } catch (error: unknown) {
    clearTimeout(timeoutId);
    if (error instanceof Error && error.name === 'AbortError') {
      return errorResponse('timeout', 504);
    }
    console.error('[feed] API error:', error);
    return errorResponse('api_error', 502);
  }
}
